# Generated by Django 5.1.3 on 2024-11-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nmcnpmapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment",
        ),
    ]
