# Generated by Django 5.1.3 on 2024-11-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmcnpmapp", "0002_remove_payment_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familymember",
            name="age",
        ),
        migrations.AddField(
            model_name="familymember",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(),
        ),
    ]
