# Generated by Django 5.1.3 on 2024-11-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nmcnpmapp",
            "0003_remove_familymember_age_familymember_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="category",
            field=models.CharField(default="Others", max_length=100),
        ),
    ]
