# Generated by Django 5.1.3 on 2024-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0003_superuser_groups_superuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
