# Generated by Django 5.1.3 on 2024-11-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0004_roomuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomuser',
            name='is_approved',
        ),
    ]
