# Generated by Django 5.1.3 on 2024-11-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmcnpmapp", "0004_charge_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="category",
            field=models.CharField(
                choices=[
                    ("electricity", "Tiền điện"),
                    ("water", "Tiền nước"),
                    ("service_fee", "Phí dịch vụ"),
                    ("management_fee", "Phí quản lý"),
                    ("other", "Khác"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
