# Generated by Django 5.1.3 on 2024-11-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0005_remove_roomuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
