# Generated by Django 5.1.3 on 2024-12-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0006_alter_article_options_alter_charge_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='nmcnpmapp.apartment', verbose_name='Số phòng')),
            ],
            options={
                'verbose_name': 'Quản lý thông báo',
                'verbose_name_plural': 'Quản lý thông báo',
            },
        ),
    ]
