# Generated by Django 5.1.3 on 2024-12-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0007_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Quản lý thông báo các hộ', 'verbose_name_plural': 'Quản lý thông báo các hộ'},
        ),
    ]
