# Generated by Django 5.1.3 on 2024-12-11 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0008_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Thông báo', 'verbose_name_plural': 'Quản lý thông báo'},
        ),
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': 'Khoản thu', 'verbose_name_plural': 'Quản lý khoản thu'},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': 'Nhân khẩu', 'verbose_name_plural': 'Quản lý nhân khẩu'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Khoản thanh toán', 'verbose_name_plural': 'Quản lý khoản thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='roomuser',
            options={'verbose_name': 'Tài khoản', 'verbose_name_plural': 'Quản lý tài khoản'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Thông tin gửi xe', 'verbose_name_plural': 'Quản lý gửi xe'},
        ),
    ]
