# Generated by Django 5.1.3 on 2024-11-09 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0011_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='donggop',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dongphi',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sukien',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0123456789', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registry_email',
            field=models.EmailField(default='lol@gamil.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customuser',
            name='room_id',
            field=models.CharField(auto_created=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(default=13),
        ),
        migrations.AddField(
            model_name='familymember',
            name='phone_number',
            field=models.CharField(default='0123456789', max_length=10),
        ),
        migrations.AddField(
            model_name='familymember',
            name='room_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL, to_field='room_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='email',
            field=models.EmailField(default='lol@gamil.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='nmcnpmapp.payment')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_statuses', to=settings.AUTH_USER_MODEL, to_field='room_id')),
            ],
        ),
    ]
