# Generated by Django 5.1.3 on 2024-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmcnpmapp', '0012_payment_remove_customuser_donggop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='room_id',
            field=models.CharField(default='000000', max_length=100, unique=True),
        ),
    ]
